apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone-test-context
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: output
      emptyDir: {}
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/wsdtsh159359/tekton.git
    - name: revision
      value: release
