FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.24.0@sha256:631e7b24d2233854e0fc7d7deab15838b14c9fdd86fbd3bc38658ebcc203eac0
MAINTAINER gaowei <wsdtsh159357@gmail.com>
